# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d50f8ea9fdb5d1244a40b293f078ad70ad536132bb4bca391089944591c3719e37d9ac4ee1993d3e0d97d7d78d1a5dbf84d2968f0ddf977f55f3de36e17f6c3

test:
  secret_key_base: d6fc77f44feda4c233cc6aedcaeb3a389be2096b0582f5994d4f0f0185036c6c9e3854ff23d00e5447b933d3bc4cfd480ed37635d6add0841e6b34572a7f1b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
